#############################################################################
# Makefile for building: CharacterSheet
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Mar 13 14:31:22 2013
# Project:  DDCharacterSheet.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile DDCharacterSheet.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -Iheaders -ImocFiles
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = src/caracs.cpp \
		src/competences.cpp \
		src/diceRoller.cpp \
		src/dons.cpp \
		src/equipement.cpp \
		src/main.cpp \
		src/mainWindow.cpp \
		src/rolePlay.cpp \
		src/sac.cpp \
		src/databaseManager.cpp mocFiles/moc_caracs.cpp \
		mocFiles/moc_competences.cpp \
		mocFiles/moc_diceRoller.cpp \
		mocFiles/moc_dons.cpp \
		mocFiles/moc_equipement.cpp \
		mocFiles/moc_mainWindow.cpp \
		mocFiles/moc_rolePlay.cpp \
		mocFiles/moc_sac.cpp \
		mocFiles/moc_databaseManager.cpp
OBJECTS       = bin/caracs.o \
		bin/competences.o \
		bin/diceRoller.o \
		bin/dons.o \
		bin/equipement.o \
		bin/main.o \
		bin/mainWindow.o \
		bin/rolePlay.o \
		bin/sac.o \
		bin/databaseManager.o \
		bin/moc_caracs.o \
		bin/moc_competences.o \
		bin/moc_diceRoller.o \
		bin/moc_dons.o \
		bin/moc_equipement.o \
		bin/moc_mainWindow.o \
		bin/moc_rolePlay.o \
		bin/moc_sac.o \
		bin/moc_databaseManager.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		DDCharacterSheet.pro
QMAKE_TARGET  = CharacterSheet
DESTDIR       = 
TARGET        = CharacterSheet

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DDCharacterSheet.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile DDCharacterSheet.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile DDCharacterSheet.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/CharacterSheet1.0.0 || $(MKDIR) bin/CharacterSheet1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/CharacterSheet1.0.0/ && $(COPY_FILE) --parents headers/caracs.h headers/competences.h headers/diceRoller.h headers/dons.h headers/equipement.h headers/mainWindow.h headers/rolePlay.h headers/sac.h headers/databaseManager.h bin/CharacterSheet1.0.0/ && $(COPY_FILE) --parents src/caracs.cpp src/competences.cpp src/diceRoller.cpp src/dons.cpp src/equipement.cpp src/main.cpp src/mainWindow.cpp src/rolePlay.cpp src/sac.cpp src/databaseManager.cpp bin/CharacterSheet1.0.0/ && (cd `dirname bin/CharacterSheet1.0.0` && $(TAR) CharacterSheet1.0.0.tar CharacterSheet1.0.0 && $(COMPRESS) CharacterSheet1.0.0.tar) && $(MOVE) `dirname bin/CharacterSheet1.0.0`/CharacterSheet1.0.0.tar.gz . && $(DEL_FILE) -r bin/CharacterSheet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: mocFiles/moc_caracs.cpp mocFiles/moc_competences.cpp mocFiles/moc_diceRoller.cpp mocFiles/moc_dons.cpp mocFiles/moc_equipement.cpp mocFiles/moc_mainWindow.cpp mocFiles/moc_rolePlay.cpp mocFiles/moc_sac.cpp mocFiles/moc_databaseManager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) mocFiles/moc_caracs.cpp mocFiles/moc_competences.cpp mocFiles/moc_diceRoller.cpp mocFiles/moc_dons.cpp mocFiles/moc_equipement.cpp mocFiles/moc_mainWindow.cpp mocFiles/moc_rolePlay.cpp mocFiles/moc_sac.cpp mocFiles/moc_databaseManager.cpp
mocFiles/moc_caracs.cpp: headers/databaseManager.h \
		headers/caracs.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/caracs.h -o mocFiles/moc_caracs.cpp

mocFiles/moc_competences.cpp: headers/databaseManager.h \
		headers/competences.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/competences.h -o mocFiles/moc_competences.cpp

mocFiles/moc_diceRoller.cpp: headers/diceRoller.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/diceRoller.h -o mocFiles/moc_diceRoller.cpp

mocFiles/moc_dons.cpp: headers/dons.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/dons.h -o mocFiles/moc_dons.cpp

mocFiles/moc_equipement.cpp: headers/equipement.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/equipement.h -o mocFiles/moc_equipement.cpp

mocFiles/moc_mainWindow.cpp: headers/caracs.h \
		headers/databaseManager.h \
		headers/equipement.h \
		headers/sac.h \
		headers/competences.h \
		headers/dons.h \
		headers/rolePlay.h \
		headers/diceRoller.h \
		headers/mainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/mainWindow.h -o mocFiles/moc_mainWindow.cpp

mocFiles/moc_rolePlay.cpp: headers/rolePlay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/rolePlay.h -o mocFiles/moc_rolePlay.cpp

mocFiles/moc_sac.cpp: headers/sac.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/sac.h -o mocFiles/moc_sac.cpp

mocFiles/moc_databaseManager.cpp: headers/databaseManager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/databaseManager.h -o mocFiles/moc_databaseManager.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bin/caracs.o: src/caracs.cpp headers/caracs.h \
		headers/databaseManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/caracs.o src/caracs.cpp

bin/competences.o: src/competences.cpp headers/competences.h \
		headers/databaseManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/competences.o src/competences.cpp

bin/diceRoller.o: src/diceRoller.cpp headers/diceRoller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/diceRoller.o src/diceRoller.cpp

bin/dons.o: src/dons.cpp headers/dons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/dons.o src/dons.cpp

bin/equipement.o: src/equipement.cpp headers/equipement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/equipement.o src/equipement.cpp

bin/main.o: src/main.cpp headers/mainWindow.h \
		headers/caracs.h \
		headers/databaseManager.h \
		headers/equipement.h \
		headers/sac.h \
		headers/competences.h \
		headers/dons.h \
		headers/rolePlay.h \
		headers/diceRoller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/main.o src/main.cpp

bin/mainWindow.o: src/mainWindow.cpp headers/mainWindow.h \
		headers/caracs.h \
		headers/databaseManager.h \
		headers/equipement.h \
		headers/sac.h \
		headers/competences.h \
		headers/dons.h \
		headers/rolePlay.h \
		headers/diceRoller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/mainWindow.o src/mainWindow.cpp

bin/rolePlay.o: src/rolePlay.cpp headers/rolePlay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/rolePlay.o src/rolePlay.cpp

bin/sac.o: src/sac.cpp headers/sac.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/sac.o src/sac.cpp

bin/databaseManager.o: src/databaseManager.cpp headers/databaseManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/databaseManager.o src/databaseManager.cpp

bin/moc_caracs.o: mocFiles/moc_caracs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_caracs.o mocFiles/moc_caracs.cpp

bin/moc_competences.o: mocFiles/moc_competences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_competences.o mocFiles/moc_competences.cpp

bin/moc_diceRoller.o: mocFiles/moc_diceRoller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_diceRoller.o mocFiles/moc_diceRoller.cpp

bin/moc_dons.o: mocFiles/moc_dons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_dons.o mocFiles/moc_dons.cpp

bin/moc_equipement.o: mocFiles/moc_equipement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_equipement.o mocFiles/moc_equipement.cpp

bin/moc_mainWindow.o: mocFiles/moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_mainWindow.o mocFiles/moc_mainWindow.cpp

bin/moc_rolePlay.o: mocFiles/moc_rolePlay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_rolePlay.o mocFiles/moc_rolePlay.cpp

bin/moc_sac.o: mocFiles/moc_sac.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_sac.o mocFiles/moc_sac.cpp

bin/moc_databaseManager.o: mocFiles/moc_databaseManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_databaseManager.o mocFiles/moc_databaseManager.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

