# Variables
CXX=g++
CXXFLAGS=-Wall -Wextra -g -O2
LDFLAGS=-lQtGui -lQtCore
INCLUDES=-I/usr/include/qt4 -I/usr/include/qt4/QtGui
EXEC=CharacterSheet

# Complete project compilation
all: main.o mainWindow.o competences.o caracs.o dons.o equipement.o rolePlay.o sac.o moc_caracs.o moc_mainWindow.o moc_sac.o moc_equipement.o moc_rolePlay.o
	$(CXX) $^ $(LDFLAGS) -o $(EXEC)
	@echo ''
	@echo '==> Compilation successfully done'

# Compilation of .cpp files that require the moc
mainWindow.o: mainWindow.h mainWindow.cpp
	moc -o moc_mainWindow.cpp $<
	$(CXX) -c mainWindow.cpp $(CXXFLAGS) $(INCLUDES)
sac.o: sac.h sac.cpp
	moc -o moc_sac.cpp $<
	$(CXX) -c sac.cpp $(CXXFLAGS) $(INCLUDES)
caracs.o: caracs.h caracs.cpp
	moc -o moc_caracs.cpp $<
	$(CXX) -c caracs.cpp $(CXXFLAGS) $(INCLUDES)
equipement.o: equipement.h equipement.cpp
	moc -o moc_equipement.cpp $<
	$(CXX) -c equipement.cpp $(CXXFLAGS) $(INCLUDES)
rolePlay.o: rolePlay.h rolePlay.cpp
	moc -o moc_rolePlay.cpp $<
	$(CXX) -c rolePlay.cpp $(CXXFLAGS) $(INCLUDES)

# Compilation of .cpp files that don't require the moc
%.o: %.cpp
	$(CXX) -c $< $(CXXFLAGS) $(INCLUDES)
	
# Compilation of .cpp files generated by the moc
moc_caracs.o: moc_caracs.cpp
	$(CXX) -c $< $(CXXFLAGS) $(INCLUDES)
moc_mainWindow.o: moc_mainWindow.cpp
	$(CXX) -c $< $(CXXFLAGS) $(INCLUDES)
moc_sac.o: moc_sac.cpp
	$(CXX) -c $< $(CXXFLAGS) $(INCLUDES)
moc_equipement.o: moc_equipement.cpp
	$(CXX) -c $< $(CXXFLAGS) $(INCLUDES)
moc_rolePlay.o: moc_rolePlay.cpp
	$(CXX) -c $< $(CXXFLAGS) $(INCLUDES)

# Removal of all files created during the compilation, excepting the final executable file
clean:
	rm -rf *.o *~ moc_*.cpp
# Removal of all files created during the compilation, including the final executable file
completeClean: clean
	rm -rf $(EXEC)
	
